// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rTLPzkgk3cpV4NRAVqpS2D

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { Web3GlobalContext } from "suinova-nft-builder/dist/index.js";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  web3GlobalContextProps?: Partial<
    Omit<React.ComponentProps<typeof Web3GlobalContext>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, web3GlobalContextProps } = props;

  return (
    <Web3GlobalContext
      {...web3GlobalContextProps}
      apiUrl={
        web3GlobalContextProps && "apiUrl" in web3GlobalContextProps
          ? web3GlobalContextProps.apiUrl!
          : undefined
      }
      contractPackageId={
        web3GlobalContextProps && "contractPackageId" in web3GlobalContextProps
          ? web3GlobalContextProps.contractPackageId!
          : "0x2d99da054514ff31c7e7da82751d11bb16b53c66290c435a409e17c8992e35ed"
      }
      createdCollection={
        web3GlobalContextProps && "createdCollection" in web3GlobalContextProps
          ? web3GlobalContextProps.createdCollection!
          : "launchpadCollectionId"
      }
      importedCollection={
        web3GlobalContextProps && "importedCollection" in web3GlobalContextProps
          ? web3GlobalContextProps.importedCollection!
          : undefined
      }
    >
      {children}
    </Web3GlobalContext>
  );
}
